# user.nix -- Your personal configuration
# Generated by bootstrap wizard. Edit freely, then run: git add -f user.nix
#
# This file is gitignored to keep personal data out of the shared repo.
# It is staged with `git add -f` so Nix flakes can see it.
{
  # Required
  username = "arash";
  fullName = "Arash Haghighat";
  email = "arash@a12t.co";

  # Git signing
  git = {
    signing = {
      key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOi05F3OPxt5srdeg1gzC5JkaLE3VGTBp/PabVWwja75";
      signByDefault = true;
      format = "ssh";
      signer = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign";
    };
    allowedSigners = "arash@a12t.co ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOi05F3OPxt5srdeg1gzC5JkaLE3VGTBp/PabVWwja75";
  };

  # Feature toggles
  features = {
    onePassword = true;
  };
}
